name: Test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - run: bin/rubocop
      - run: bin/rspec
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          directory: tmp/simple_cov
